import { continueAction, reassessRouteAction } from "../manifest/interactions";
import type { CanonicalSceneDefinition } from "../manifest/sceneTypes";
import {
  FALSE_ARRIVAL_ROUTE_ID,
  GATE1_FORMAL_NAME,
  HIDDEN_PAGE_PHRASE,
  SPLINTERED_TRUST_ROUTE_ID,
} from "./constants";
import { GATE1_ASSET_KEYS } from "./assets";
import { GATE1_QUESTIONS } from "./questions";
import {
  defineGate1Scene,
  establishes,
  requiresActiveRoute,
  requiresShared,
  transitionTo,
} from "./sceneFactory.protected";
import { GATE1_VALIDATION_KEYS as V } from "./validationKeys.protected";

export const GATE1_SHARED_OPENING_SCENES: readonly CanonicalSceneDefinition[] = [
  defineGate1Scene({
    id: "G1-00",
    group: "shared_opening",
    type: "threshold",
    title: "Threshold Arrival",
    purpose: "Enter The Broken Vow intentionally",
    heading: GATE1_FORMAL_NAME,
    interaction: { kind: "acknowledgment" },
    primaryAction: continueAction("Enter the threshold"),
    assetRefs: [GATE1_ASSET_KEYS.threshold],
    establishes: [establishes(V.thresholdEntered)],
    transitions: [transitionTo("G1-01")],
  }),
  defineGate1Scene({
    id: "G1-01",
    group: "shared_opening",
    type: "symbolic_encounter",
    title: "Architecture of Agreement",
    purpose: "Encounter the conditional structure beneath a promise",
    narration: [
      "If I did my part, then ___ would follow.",
      "I believed ___ would protect me from ___.",
    ],
    assetRefs: [GATE1_ASSET_KEYS.agreement],
    prerequisites: [requiresShared(V.thresholdEntered)],
    establishes: [establishes(V.agreementRecognized)],
    transitions: [transitionTo("G1-02")],
  }),
  defineGate1Scene({
    id: "G1-02",
    group: "shared_opening",
    type: "symbol_behavior",
    title: "The Inscription Fractures",
    purpose: "See one agreement fracture while the larger structure remains",
    narration: [
      "One inscription fractures.",
      "The chamber remains standing.",
      "One agreement broke, not reality itself.",
    ],
    reducedMotionEquivalent:
      "One inscription is shown fractured while the chamber remains standing: one agreement broke, not reality itself.",
    screenReaderSequence: [
      "One inscription fractures.",
      "The chamber remains standing.",
      "One agreement broke, not reality itself.",
    ],
    prerequisites: [requiresShared(V.agreementRecognized)],
    establishes: [establishes(V.inscriptionFractured)],
    transitions: [transitionTo("G1-03")],
  }),
  defineGate1Scene({
    id: "G1-03",
    group: "shared_opening",
    type: "recognition",
    title: "Event and Promise Separate",
    purpose: "Distinguish what happened from what was believed",
    narration: ["What happened", "from", "What was expected to follow"],
    interaction: { kind: "reflection" },
    prerequisites: [requiresShared(V.inscriptionFractured)],
    establishes: [establishes(V.eventPromiseSeparated)],
    transitions: [transitionTo("G1-04")],
  }),
  defineGate1Scene({
    id: "G1-04",
    group: "shared_opening",
    type: "oracle_distinction",
    title: "Oracle Distinction",
    purpose: "Establish that broken expectation and broken reality are not identical",
    narration: [
      "Event ≠ Promise",
      "Recognition ≠ Freedom",
      "Suspicion ≠ Sovereignty",
      "Planning ≠ Reality contact",
    ],
    prerequisites: [requiresShared(V.eventPromiseSeparated)],
    establishes: [establishes(V.oracleDistinctionEstablished)],
    transitions: [transitionTo("G1-05")],
  }),
  defineGate1Scene({
    id: "G1-05",
    group: "shared_opening",
    type: "recognition",
    title: "Promise Recognition",
    purpose: "Complete an inherited conditional agreement",
    narration: [
      "If I did my part, then ___ would follow.",
      "I believed ___ would protect me from ___.",
    ],
    interaction: { kind: "reflection" },
    prerequisites: [requiresShared(V.oracleDistinctionEstablished)],
    establishes: [establishes(V.promiseRecognitionCompleted)],
    transitions: [transitionTo("G1-06")],
  }),
  defineGate1Scene({
    id: "G1-06",
    group: "shared_opening",
    type: "question",
    title: "Bridge Question",
    purpose: "Name what was expected to preserve coherence",
    prompt: GATE1_QUESTIONS.bridge.prompt,
    interaction: { kind: "reflection" },
    prerequisites: [requiresShared(V.promiseRecognitionCompleted)],
    establishes: [establishes(V.bridgeAnswered)],
    transitions: [transitionTo("G1-07")],
    protected: { canonicalQuestionId: GATE1_QUESTIONS.bridge.canonicalQuestionId },
  }),
  defineGate1Scene({
    id: "G1-07",
    group: "shared_opening",
    type: "question",
    title: "Gate Axis Question",
    purpose: "Name the promise of the world that broke",
    prompt: GATE1_QUESTIONS.gateAxis.prompt,
    interaction: { kind: "reflection" },
    prerequisites: [requiresShared(V.bridgeAnswered)],
    establishes: [establishes(V.gateAxisAnswered)],
    transitions: [transitionTo("G1-08")],
    protected: { canonicalQuestionId: GATE1_QUESTIONS.gateAxis.canonicalQuestionId },
  }),
  defineGate1Scene({
    id: "G1-08",
    group: "shared_opening",
    type: "narration",
    title: "Obstruction",
    purpose: "Reveal that seeing fracture does not by itself create passage",
    prerequisites: [requiresShared(V.gateAxisAnswered)],
    establishes: [establishes(V.obstructionEstablished)],
    transitions: [transitionTo("G1-09")],
  }),
  defineGate1Scene({
    id: "G1-09",
    group: "shared_opening",
    type: "recognition",
    title: "Stance Recognition",
    purpose: "Select one participant-safe stance statement",
    interaction: {
      kind: "stance_selection",
      options: [
        "I see what was false. I am no longer bound by it.",
        "I see what was false. I cannot trust what comes next.",
      ],
    },
    prerequisites: [requiresShared(V.obstructionEstablished)],
    establishes: [establishes(V.stanceRecognized)],
    transitions: [transitionTo("G1-10")],
  }),
  defineGate1Scene({
    id: "G1-10",
    group: "shared_opening",
    type: "book_emergence",
    title: "Book Emergence",
    purpose: "The Book of Spiral Fractures enters the field",
    assetRefs: [GATE1_ASSET_KEYS.book],
    prerequisites: [requiresShared(V.stanceRecognized)],
    establishes: [establishes(V.bookEmerged)],
    transitions: [transitionTo("G1-11")],
  }),
  defineGate1Scene({
    id: "G1-11",
    group: "shared_opening",
    type: "hidden_page",
    title: "Hidden Page Awakens",
    purpose: "Deliver the concealed page without route title",
    heading: HIDDEN_PAGE_PHRASE,
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresShared(V.bookEmerged)],
    transitions: [
      transitionTo("FA-01", FALSE_ARRIVAL_ROUTE_ID),
      transitionTo("ST-01", SPLINTERED_TRUST_ROUTE_ID),
    ],
  }),
];

export const GATE1_SHARED_CLOSING_SCENES: readonly CanonicalSceneDefinition[] = [
  defineGate1Scene({
    id: "G1-12",
    group: "shared_closing",
    type: "readiness",
    title: "Final Readiness Encounter",
    purpose: "Ask whether anything changed outside the page",
    prompt: GATE1_QUESTIONS.finalReadiness.prompt,
    interaction: { kind: "reflection" },
    secondaryAction: reassessRouteAction(),
    prerequisites: [
      requiresShared(V.bridgeAnswered),
      requiresShared(V.gateAxisAnswered),
      requiresShared(V.stanceRecognized),
      requiresActiveRoute(V.gateActFormed),
      requiresActiveRoute(V.qualifyingEvidence),
    ],
    establishes: [establishes(V.readinessConfirmed)],
    transitions: [transitionTo("G1-13")],
    protected: { canonicalQuestionId: GATE1_QUESTIONS.finalReadiness.canonicalQuestionId },
  }),
  defineGate1Scene({
    id: "G1-13",
    group: "shared_closing",
    type: "corrective_gate",
    title: "Corrective Gate Opens",
    purpose: "Open passage after evidence and readiness",
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresShared(V.readinessConfirmed)],
    establishes: [establishes(V.correctiveGateOpened)],
    transitions: [transitionTo("G1-14")],
  }),
  defineGate1Scene({
    id: "G1-14",
    group: "shared_closing",
    type: "page_seal",
    title: "Hidden Page Seals",
    purpose: "Seal the active page with its protected route line",
    semanticSummary: "Seal the active hidden page with its closing line",
    primaryAction: { label: "Seal the hidden page", intent: "seal" },
    prerequisites: [requiresShared(V.correctiveGateOpened)],
    establishes: [establishes(V.hiddenPageSealed)],
    transitions: [transitionTo("G1-15")],
  }),
  defineGate1Scene({
    id: "G1-15",
    group: "shared_closing",
    type: "book_withdrawal",
    title: "Book Withdraws",
    purpose: "Relock and withdraw the Book",
    prerequisites: [requiresShared(V.hiddenPageSealed)],
    establishes: [establishes(V.bookWithdrawn)],
    transitions: [transitionTo("G1-16")],
  }),
  defineGate1Scene({
    id: "G1-16",
    group: "shared_closing",
    type: "completion",
    title: "Gate Completion",
    purpose: "Record Gate 1 completion",
    primaryAction: { label: "Complete the gate", intent: "complete" },
    prerequisites: [requiresShared(V.bookWithdrawn)],
    establishes: [establishes(V.gateCompleted)],
  }),
];
