import { continueAction, reassessRouteAction } from "../manifest/interactions";
import type { CanonicalSceneDefinition } from "../manifest/sceneTypes";
import { SPLINTERED_TRUST_ROUTE_ID } from "./constants";
import { GATE1_ASSET_KEYS } from "./assets";
import { GATE1_QUESTIONS } from "./questions";
import {
  defineGate1Scene,
  establishes,
  requiresActiveRoute,
  requiresShared,
  transitionTo,
} from "./sceneFactory.protected";
import { GATE1_VALIDATION_KEYS as V } from "./validationKeys.protected";
import { GATE1_PROTECTED_ROUTE_MAP } from "./routeBindings.protected";

const route = GATE1_PROTECTED_ROUTE_MAP[SPLINTERED_TRUST_ROUTE_ID];
const protectedRoute = { routeId: SPLINTERED_TRUST_ROUTE_ID } as const;

export const GATE1_SPLINTERED_TRUST_SCENES: readonly CanonicalSceneDefinition[] = [
  defineGate1Scene({
    id: "ST-01",
    group: "splintered_trust",
    type: "symbolic_encounter",
    title: "Broken Compass",
    purpose: "Encounter a compass no longer pointing to external authority",
    assetRefs: [GATE1_ASSET_KEYS.symbolB],
    primaryAction: continueAction(),
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresShared(V.bookEmerged)],
    establishes: [establishes(V.activeRouteSymbolEncountered)],
    transitions: [transitionTo("ST-02")],
    protected: protectedRoute,
  }),
  defineGate1Scene({
    id: "ST-02",
    group: "splintered_trust",
    type: "oracle_distinction",
    title: "Signal Without Authority",
    purpose: "Distinguish discernment from total distrust",
    narration: [route.symbolicLaw, route.oracleDistinction],
    primaryAction: continueAction(),
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresActiveRoute(V.activeRouteSymbolEncountered)],
    establishes: [establishes(V.activeRouteDistinctionEstablished)],
    transitions: [transitionTo("ST-03")],
    protected: protectedRoute,
  }),
  defineGate1Scene({
    id: "ST-03",
    group: "splintered_trust",
    type: "question",
    title: "Route Axis Question",
    purpose: "Ask the exact Splintered Trust Axis Question",
    semanticSummary: "Ask the active hidden-page axis question",
    prompt: GATE1_QUESTIONS.splinteredTrustAxis.prompt,
    interaction: { kind: "reflection" },
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresActiveRoute(V.activeRouteDistinctionEstablished)],
    establishes: [establishes(V.routeAxisAnswered)],
    transitions: [transitionTo("ST-04")],
    protected: {
      ...protectedRoute,
      canonicalQuestionId: GATE1_QUESTIONS.splinteredTrustAxis.canonicalQuestionId,
    },
  }),
  defineGate1Scene({
    id: "ST-04",
    group: "splintered_trust",
    type: "question",
    title: "Broken Trust",
    purpose: "Name what broke trust",
    prompt: "Name what broke trust.",
    interaction: { kind: "reflection" },
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresActiveRoute(V.routeAxisAnswered)],
    establishes: [establishes(V.routePromptOneAnswered)],
    transitions: [transitionTo("ST-05")],
    protected: protectedRoute,
  }),
  defineGate1Scene({
    id: "ST-05",
    group: "splintered_trust",
    type: "question",
    title: "Protective Suspicion",
    purpose: "Name how suspicion currently protects",
    prompt: "Name how suspicion currently protects.",
    interaction: { kind: "reflection" },
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresActiveRoute(V.routePromptOneAnswered)],
    establishes: [establishes(V.routePromptTwoAnswered)],
    transitions: [transitionTo("ST-06")],
    protected: protectedRoute,
  }),
  defineGate1Scene({
    id: "ST-06",
    group: "splintered_trust",
    type: "question",
    title: "Authority Pattern",
    purpose: "Name the pattern equating authority with truth",
    prompt: "Name the pattern equating authority with truth.",
    interaction: { kind: "reflection" },
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresActiveRoute(V.routePromptTwoAnswered)],
    establishes: [establishes(V.routePromptThreeAnswered)],
    transitions: [transitionTo("ST-07")],
    protected: protectedRoute,
  }),
  defineGate1Scene({
    id: "ST-07",
    group: "splintered_trust",
    type: "question",
    title: "Remaining Signal",
    purpose: "Name a bounded signal available without surrender",
    prompt: "Name a bounded signal available without surrender.",
    interaction: { kind: "reflection" },
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresActiveRoute(V.routePromptThreeAnswered)],
    establishes: [establishes(V.routePromptFourAnswered)],
    transitions: [transitionTo("ST-08")],
    protected: protectedRoute,
  }),
  defineGate1Scene({
    id: "ST-08",
    group: "splintered_trust",
    type: "gate_act",
    title: "Discerned Trust Formation",
    purpose: "Form one reversible, bounded signal test",
    interaction: { kind: "gate_act" },
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresActiveRoute(V.routePromptFourAnswered)],
    establishes: [establishes(V.gateActFormed)],
    transitions: [transitionTo("ST-09")],
    protected: protectedRoute,
  }),
  defineGate1Scene({
    id: "ST-09",
    group: "splintered_trust",
    type: "evidence",
    title: "Reality Contact",
    purpose: "Record one immediate micro-act outside reflection",
    interaction: { kind: "evidence" },
    secondaryAction: reassessRouteAction(),
    prerequisites: [requiresActiveRoute(V.gateActFormed)],
    establishes: [establishes(V.qualifyingEvidence)],
    transitions: [transitionTo("G1-12")],
    protected: protectedRoute,
  }),
];
