export const GATE1_VALIDATION_KEYS = {
  thresholdEntered: "g1.threshold_entered",
  agreementRecognized: "g1.agreement_recognized",
  inscriptionFractured: "g1.inscription_fractured",
  eventPromiseSeparated: "g1.event_promise_separated",
  oracleDistinctionEstablished: "g1.oracle_distinction_established",
  promiseRecognitionCompleted: "g1.promise_recognition_completed",
  bridgeAnswered: "g1.bridge_answered",
  gateAxisAnswered: "g1.gate_axis_answered",
  obstructionEstablished: "g1.obstruction_established",
  stanceRecognized: "g1.stance_recognized",
  bookEmerged: "g1.book_emerged",
  activeRouteSymbolEncountered: "g1.active_route_symbol_encountered",
  activeRouteDistinctionEstablished: "g1.active_route_distinction_established",
  routeAxisAnswered: "g1.route_axis_answered",
  routePromptOneAnswered: "g1.active_route_prompt_one_answered",
  routePromptTwoAnswered: "g1.active_route_prompt_two_answered",
  routePromptThreeAnswered: "g1.active_route_prompt_three_answered",
  routePromptFourAnswered: "g1.active_route_prompt_four_answered",
  gateActFormed: "g1.active_route_gate_act_formed",
  qualifyingEvidence: "g1.active_route_qualifying_evidence",
  readinessConfirmed: "g1.readiness_confirmed",
  correctiveGateOpened: "g1.corrective_gate_opened",
  hiddenPageSealed: "g1.hidden_page_sealed",
  bookWithdrawn: "g1.book_withdrawn",
  gateCompleted: "g1.completed",
} as const;
