import { z } from "zod";

export const EvaluationReasonCodeSchema = z.enum([
  "directly_answers_prompt",
  "names_specific_event",
  "names_expected_promise",
  "names_current_pattern",
  "names_personal_relevance",
  "distinguishes_event_from_promise",
  "distinguishes_recognition_from_freedom",
  "distinguishes_discernment_from_total_distrust",
  "identifies_outside_change",
  "empty_or_missing",
  "explicit_not_yet_formed",
  "nonresponsive",
  "too_abstract",
  "only_repeats_prompt",
  "only_intellectual_summary",
  "missing_specific_event",
  "missing_expected_promise",
  "missing_present_pattern",
  "externalizes_all_agency",
  "contradictory_to_required_facets",
  "low_confidence",
  "follow_up_limit_reached",
  "act_is_bounded",
  "act_is_observable",
  "act_is_participant_controlled",
  "act_is_reversible",
  "act_is_route_relevant",
  "act_is_too_broad",
  "act_depends_on_other_person",
  "act_is_irreversible",
  "act_is_high_cost",
  "act_is_confrontational",
  "act_is_illegal_or_policy_prohibited",
  "act_is_not_observable",
  "act_is_unrelated_to_gate",
  "completed_outside_reflection",
  "matches_active_gate_act",
  "scheduled_only",
  "description_missing_when_required",
  "does_not_match_gate_act",
  "only_planning",
  "only_understanding",
  "outside_change_not_named",
]);

export type EvaluationReasonCode = z.infer<typeof EvaluationReasonCodeSchema>;

export const ALL_EVALUATION_REASON_CODES = EvaluationReasonCodeSchema.options;
