/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SovereignRouteImport } from './routes/sovereign'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GatesIndexRouteImport } from './routes/gates.index'
import { Route as GateGateIdRouteImport } from './routes/gate.$gateId'

const SovereignRoute = SovereignRouteImport.update({
  id: '/sovereign',
  path: '/sovereign',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesIndexRoute = GatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatesRoute,
} as any)
const GateGateIdRoute = GateGateIdRouteImport.update({
  id: '/gate/$gateId',
  path: '/gate/$gateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/gates': typeof GatesRouteWithChildren
  '/sovereign': typeof SovereignRoute
  '/gate/$gateId': typeof GateGateIdRoute
  '/gates/': typeof GatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/sovereign': typeof SovereignRoute
  '/gate/$gateId': typeof GateGateIdRoute
  '/gates': typeof GatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/gates': typeof GatesRouteWithChildren
  '/sovereign': typeof SovereignRoute
  '/gate/$gateId': typeof GateGateIdRoute
  '/gates/': typeof GatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabinet'
    | '/gates'
    | '/sovereign'
    | '/gate/$gateId'
    | '/gates/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cabinet' | '/sovereign' | '/gate/$gateId' | '/gates'
  id:
    | '__root__'
    | '/'
    | '/cabinet'
    | '/gates'
    | '/sovereign'
    | '/gate/$gateId'
    | '/gates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetRoute: typeof CabinetRoute
  GatesRoute: typeof GatesRouteWithChildren
  SovereignRoute: typeof SovereignRoute
  GateGateIdRoute: typeof GateGateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sovereign': {
      id: '/sovereign'
      path: '/sovereign'
      fullPath: '/sovereign'
      preLoaderRoute: typeof SovereignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates/': {
      id: '/gates/'
      path: '/'
      fullPath: '/gates/'
      preLoaderRoute: typeof GatesIndexRouteImport
      parentRoute: typeof GatesRoute
    }
    '/gate/$gateId': {
      id: '/gate/$gateId'
      path: '/gate/$gateId'
      fullPath: '/gate/$gateId'
      preLoaderRoute: typeof GateGateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GatesRouteChildren {
  GatesIndexRoute: typeof GatesIndexRoute
}

const GatesRouteChildren: GatesRouteChildren = {
  GatesIndexRoute: GatesIndexRoute,
}

const GatesRouteWithChildren = GatesRoute._addFileChildren(GatesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetRoute: CabinetRoute,
  GatesRoute: GatesRouteWithChildren,
  SovereignRoute: SovereignRoute,
  GateGateIdRoute: GateGateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
